#!/usr/bin/env bash
php think menu -c dashboard
php think menu -c general/config
php think menu -c general/attachment
php think menu -c general/profile
php think menu -c category
php think menu -c auth/admin
php think menu -c auth/adminlog
php think menu -c auth/group
php think menu -c auth/rule
#php think menu -c addon
#php think menu -c user/user
#php think menu -c user/group
#php think menu -c user/rule
php think menu -c team/team
php think menu -c production/production
php think menu -c production/review
php think menu -c production/select
php think menu -c production/url
php think menu -c production/share
php think menu -c order/order
php think menu -c order/sharedata
php think menu -c order/ordertest
php think menu -c order/export
php think menu -c express/express
php think menu -c express/sms
php think menu -c sysconfig/pay
php think menu -c sysconfig/consumables
php think menu -c sysconfig/kzdomain
php think menu -c sysconfig/ground
php think menu -c sysconfig/wxdomain
php think menu -c sysconfig/xpay
php think menu -c sysconfig/rypay
php think menu -c sysconfig/payset
php think menu -c sysconfig/record
php think menu -c sysconfig/smsconfig
php think menu -c data/visit
php think menu -c data/day
php think menu -c data/summary
php think menu -c data/analysis